### ISSUE TITLE
[sugestion] normalisation of data

### ISSUE THREAD

**Issue by NuxitBrain** [be-smith/navani#6]
hi all 

here some sugestion, during the importation of the raw data, you should be able to create no collum to normalize curent and capacity by surface ( mAh/cm2 and mA/cm2) or by the mass (mAh/g or mA/g) 

maybe during the comand ec.echem_file_loader , it can be added some optionnal parameter where you can enter the active surface and mass ... 
 
have good hollyday

**Comment by ml-evs** [comment]
thanks for the good suggestion @NuxitBrain, most of the active development right now is happening on the fork at https://github.com/the-grey-group/navani, I'll consider adding it over there!

**Comment by be-smith** [comment]
This has been added now - there are optional mass and area varaibles in echem_file_loader. Currently named:
Specific Capacity
Specific Capacity (Area)
Specific Current
Current Density

If anyone has better naming suggestions let me know!
